language: erlang # wither art thou, Go?

install:
 - hg clone -r go1.0.2 https://code.google.com/p/go $HOME/go
 - cd $HOME/go/src && ./make.bash
 - mkdir -p $HOME/src || true
 - mkdir -p $HOME/bin || true
 - mkdir -p $HOME/pkg || true
 - export GOPATH=$HOME
 - export PATH=$PATH:$HOME/go/bin
 - ln -s $HOME/builds/streadway/amqp $HOME/src/amqp

script:
 - cd $HOME/src/amqp && pwd && echo $GOPATH && go build -v .
 - cd $HOME/src/amqp && pwd && echo $GOPATH && AMQP_URL=amqp://guest:guest@localhost:5672/ go test -v .

